<?php
$arr = [
	"Dashboard",
	"Useful Links",
	"Pay Now",
	"Role List",
	"Change Password",
	"Change",
	"Remove",
	"Current password",
	"Enter your current password",
	"Enter new password",
	"Repeat password",
	"Please confirm your password before continuing",
	"Password",
	"Coverage",
	"Area",
	"KG parcel",
	"Confirm Password",
	"Forgot Your Password",
	"Reset Password",
	"Forget password",
	"Email address",
	"Submit",
	"We are currently available in",
	"Districts",
	"New Password",
	"Confirm New Password",
	"2 Step Verification",
	"twoFA security",
	"2 FA Code",
	"Varification Code",
	"Email Verification",
	"Code",
	"Resend code",
	"Didn't get code?",
	"SMS Verification",
	"Sms Verification",
	"sms verification",
	"Login",
	"Sing In",
	"Username or Email",
	"Remember me",
	"Forgot Password",
	"Log In",
	"Create account",
	"Don't have an account?",
	"Sign Up",
	"register",
	"Enter Full Name",
	"Enter Email",
	"Enter Username",
	"Your Phone Number",
	"Re-type Password",
	"I Agree with the Terms &amp; conditions",
	"Login Here",
	"Already have an account?",
	"403 Forbidden",
	"Forbidden",
	"You don't have permission to access ‘/’ on this server",
	"Back To Home",
	"Back",
	"The page you’re looking for can’t be found.",
	"Please check if your spelling is correct and try again",
	"GO TO HOME",
	"Home",
	"404",
	"405",
	"419",
	"500",
	"Method Not Allowed",
	"Sorry, your session has expired",
	"Internal Server Error",
	"The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
	"All rights reserved by",
	"All Rights Reserved",
	"Copyright",
	"logo image",
	"Shipments",
	"All Shipments",
	"In Queue",
	"Dispatch",
	"Received",
	"Delivered",
	"Shipment Request",
	"Receiver List",
	"Add Fund",
	"Fund History",
	"Payout",
	"Payout History",
	"Money Transfer",
	"Transaction",
	"logo",
	"Quick Links",
	"FAQ",
	"Subscribe",
	"enter email",
	"Newsletter",
	"All rights reserved",
	"by",
	"About",
	"Service",
	"Tracking",
	"Blog",
	"Contact",
	"success",
	"error",
	"warning",
	"Previous",
	"Next",
	"current",
	"You have no notifications",
	"Clear All",
	"user profile",
	"My Profile",
	"Log Out",
	"Happy Clients",
	"Total Shipments",
	"about_image",
	"READ MORE",
	"Add Fund Preview",
	"Preview Deposit",
	"Gateway",
	"Name",
	"Currency",
	"Amount",
	"Charge",
	"Payable amount",
	"Payable",
	"Confirm",
	"Conversion Rate",
	"You can deposit money into your own wallet",
	"Deposit",
	"Details",
	"Select Payment Method",
	"Fund List",
	"Method",
	"Transaction ID",
	"Requested Amount",
	"Status",
	"Created time",
	"Success",
	"Pending",
	"Fund Added List",
	"Fund Requested List",
	"Rejected",
	"No data found",
	"Min Amount",
	"Maximum Amount",
	"Select Date",
	"Search",
	"Shipment Type",
	"Shipment Date",
	"Select date",
	"Estimate Delivery Date",
	"delivery date",
	"Sender Branch",
	"Receiver Branch",
	"Select Branch",
	"Sender",
	"Receiver",
	"From Country",
	"Select Country",
	"Select State",
	"optional",
	"Select City",
	"To Country",
	"Payment By",
	"Payment Type",
	"Select Payment Type",
	"From Wallet",
	"Cash",
	"Packing Service",
	"Yes",
	"No",
	"Add More",
	"Select package",
	"Select Variant",
	"price",
	"quantity",
	"total cost",
	"Cost",
	"Total Price",
	"Shipment Parcel Information",
	"Parcel Quantity",
	"Parcel Type",
	"Select Parcel Type",
	"Select Unit",
	"Select Parcel Unit",
	"Cost per unit",
	"kg",
	"Dimensions",
	"[Length x Width x Height](cm)",
	"Total Unit",
	"Summary",
	"Pickup Cost",
	"Supply Cost",
	"Shipping Cost",
	"Tax",
	"Insurance",
	"Total Pay",
	"Save",
	"Get Amount From Receiver",
	"From State",
	"Select Area",
	"To State",
	"Parcel Details",
	"Parcel Name",
	"Attatchments",
	"Pay with",
	"Your Card Information",
	"Enter your card number",
	"Enter the name on your card",
	"Payment Preview",
	"PLEASE SEND EXACTLY",
	"SCAN TO SEND",
	"Please Pay",
	"Pay with Khalti",
	"Confirm Now",
	"Pay with PAYPAL",
	"Pay with VoguePay",
	"Select Transfer",
	"Select Bank Currency",
	"Select Currency",
	"Select Bank",
	"Send Request",
	"Payout Method",
	"Request Amount",
	"Charge Amount",
	"Total Payable",
	"Available Balance",
	"Exchange rate",
	"You will get",
	"Choose File",
	"Select Recipient Type",
	"Select Recipient",
	"phone",
	"Paypal Id",
	"Payout List",
	"Action",
	"Generated",
	"Payment Done",
	"Canceled",
	"Type Here",
	"All Payment",
	"Pending Payment",
	"Complete Payment",
	"Rejected Payment",
	"Time",
	"Detail",
	"Cancel",
	"Complete",
	"No Data Found!",
	"Transactions",
	"Admin Feedback",
	"Close",
	"PAYOUT NOW",
	"Transaction Limit",
	"Payout By",
	"Additional Information To Withdraw Confirm",
	"Send Payout Request",
	"Withdraw your money from here",
	"Choose a payout method",
	"Continue",
	"Fixed charge",
	"Percentage charge",
	"Min limit",
	"Max limit",
	"Update",
	"Profile Information",
	"Password Setting",
	"Full Name",
	"full name",
	"Username",
	"Email",
	"email",
	"Phone",
	"Preferred Language",
	"select language",
	"Address",
	"Enter Current Password",
	"Create Receiver",
	"Create New Receiver",
	"create reveiver",
	"Receiver Lists",
	"Branch",
	"Join Date",
	"Shipment List",
	"Operator Country",
	"Internationally",
	"Create Shipment",
	"Shipment Id",
	"SL",
	"Requested",
	"Assigned Driver For Pickup",
	"Delivery In Queue",
	"Return In Queue",
	"Return In Dispatch",
	"Return In Received",
	"Return Delivered",
	"Cancel Request",
	"Delete",
	"Confirmation",
	"Are you sure to cancel this shipment request?",
	"Create New Shipment",
	"Are you sure to delete this shipment request?",
	"Drop Off",
	"Condition",
	"Shipment Details",
	"Print",
	"Return In Delivered",
	"Dispatched Time",
	"Received Time",
	"Return Dispatched Time",
	"Return Received Time",
	"Return Delivered Time",
	"Delivered Time",
	"Payment To Sender",
	"Payment Receive Time",
	"Shipment Refund Date",
	"Shipment Refund Time",
	"Parcel Information",
	"Package",
	"Variant",
	"shipment Attachments",
	"Payment Calculation",
	"Discount",
	"Sub Total",
	"pickup",
	"Create Ticket",
	"Subject",
	"Message",
	"Submit Ticket",
	"Tickets Log",
	"Create new ticket",
	"Last Reply",
	"Open",
	"Answered",
	"Closed",
	"View",
	"Customer Replied",
	"Are you want to close ticket",
	"Transaction List",
	"SL No",
	"Remarks",
	"Remark",
	"Two Factor Authenticator",
	"Disable Two Factor Authenticator",
	"Enable Two Factor Authenticator",
	"Google Authenticator",
	"Use Google Authenticator to Scan the QR code  or use the code",
	"Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
	"DOWNLOAD APP",
	"Verify Your OTP",
	"Enter Google Authenticator Code",
	"Verify",
	"Verify Your OTP to Disable",
	"loader",
	"Current Balance",
	"Cash In",
	"Total Deposit",
	"Total Shipment Transactions",
	"Operator Country Shipments",
	"Internationally Shipments",
	"Pending Shipments",
	"In Queue Shipments",
	"Delivered Shipments",
	"Return Shipments",
	"Latest Shipments",
	"Balance Transfer",
	"Receiver Email Address",
	"Enter Password",
	"Your Password",
	"Transfer",
	"Plan Name",
	"Read More",
	"Categories",
	"Search Here",
	"Recent Blogs",
	"blog_image",
	"not found image",
	"Blog Details",
	"Share now",
	"Related Blogs",
	"Contact Us",
	"Send a massage",
	"Our Phone",
	"Our Address",
	"Tracking Order",
	"Tracking Shipment",
	"Enter your tracking code",
	"Type Shipment Id",
	"Payment Failed",
	"We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
	"it seems some issue in server to server communication. Kindly connect with administrator",
	"THANK YOU",
	"Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being wi ▶",
	"Go Back to Home",
	"Inactive",
	"Active",
	"Edit",
	"Add Roles",
	"OFF",
	"ON",
	"Accessibility",
	"Manage Branch",
	"Update Roles",
	"save",
	"update",
	"Delete Confirmation",
	"Are you sure want to delete this roles",
	"Statistics",
	"Please Verify Your Email.",
	"Before proceeding, please check your email for a verification link.",
	"If you did not receive the email",
	"click here to request another",
	"Select Sender",
	"Select Receiver",
	"Payment Status",
	"Paid",
	"Unpaid",
	"Select Payment Status",
	"Image",
	"Create Date",
	"Create Branch",
	"Shipping Calculator",
	"Calculator",
	"To City",
	"To Area",
	"Total Cost",
	"SHIPPING COST",
	"PICKUP COST",
	"SUPPLY COST",
	"TAX COST",
	"INSURANCE COST",
	"TOTAL COST",
];
return $arr;
