<?php
$arr = [
	"Payment Success",
	"THANK YOU",
	"Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being with us.",
	"Go Back to Home",
	"Copyright",
	"©",
	"All Rights Reserved",
	'payment_failed' => 'Payment Failed',
	'sorry' => 'Sorry',
	'appreciate_message' => 'We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to',
	'go_back_to_home' => 'Go Back to Home',
	'copyright' => 'Copyright',
	'all_rights_reserved' => 'All Rights Reserved',
	"Tracking",
	"Tracking Order",
	"Type Shipment Id",
	"Search",
	"Find your parcel using tracking id",
	"Requested",
	"Cancel Shipment",
	"In Queue",
	"Order Shipped",
	"Order Received",
	"Order Delivered",
	"Return Order Delivered",
	"Return Order Received",
	"Return Order Shipped",
	"Return In Queue",
	"Shipment information",
	"Tracking Number",
	"Shipment Date",
	"Elapsed After Shipment",
	"Shipment Type",
	"Shipment Status",
	"Return Processing",
	"Ready For Delivery",
	"Delivery Successfully Completed",
	"No Result Found",
	"We can’t find any results based on your search.",
	"Our Services",
	"Service",
	'Packaging Cost',
	'Packaging',
	'Box',
	'document Box Cost',
	'extra small box',
	'small box',
	'big box',
	'Box',
	'Cost',
	'KG parcel',
	'Shipping Calculator',
	'Calculator',
	'Internationally',
	'Select State',
	'Select City',
	'Select Area',
	'From State',
	'To State',
	'To City',
	'To Area',
	'Parcel Type',
	'Select Parcel Type',
	'Select Unit',
	'Cost per unit',
	'Total Unit',
	'Total Cost',
	'SHIPPING COST',
	'PICKUP COST',
	'SUPPLY COST',
	'TAX COST',
	'INSURANCE COST',
	'TOTAL COST',
	'Add More',
	'Create Shipment',
	"Shipping Calculator",
	"Calculator",
	"Internatonally",
	"Select Country",
	"Select State",
	"Select City",
	"From Country",
	"optional",
	"To Country",
	"Total Unit",
	"Total Cost",
	"SHIPPING COST",
	"PICKUP COST",
	"SUPPLY COST",
	"TAX COST",
	"INSURANCE COST",
	"TOTAL COST",
	"Create Shipment",
	"Add More",
	"Parcel Type",
	"Select Parcel Type",
	"Select Unit",
	"Cost per unit",
	"Total Cost",
	"kg",
	"THANK YOU",
	"Home",
	"FAQ",
	"Coverage Area",
	"We are currently available in",
	"Districts",
	"Countries",
	"operator-country",
	"internationally",
	"Contact Us",
	"Contact",
	"Full name",
	"Email address",
	"Subject",
	"Your message",
	"Send a massage",
	"Our Phone",
	"Email",
	"Our Address",
	"Blog Details",
	"Share now",
	"Search Here...",
	"Categories",
	"Related Blogs",
	"blog_image",
	"Payment Success",
	"THANK YOU",
	"Our Blogs",
	"Read More",
	"Search Here",
	"Categories",
	"Recent Blogs",
	"blog_image",
	"not found image",
	"Payment Success",
	"THANK YOU",
	"About Us",
	"My Profile",
	"About",
	"Payment",
	"Pay Now",
	"Transaction Limit:",
	"Charge:",
	"Payment By",
	"Amount",
	"Payable",
	"Conversion Rate",
	"Dashboard",
	"Balance Transfer",
	"Current Balance",
	"Receiver Email Address",
	"Enter Amount",
	"Enter Password",
	"Transfer",
	"Dashboard",
	"Do not miss any single important notification! Allow your browser to get instant push notification",
	"Allow me",
	"Please allow your browser to get instant push notification. Allow it from notification setting.",
	"Current Balance",
	"Total Deposit",
	"Total Shipments",
	"Total Shipment Transactions",
	"Operator Country Shipments",
	"Internationally Shipments",
	"Pending Shipments",
	"In Queue Shipments",
	"Delivered Shipments",
	"Return Shipments",
	"Latest Shipments",
	"SL.",
	"Shipment From",
	"Shipment Id",
	"Shipment Type",
	"Sender Branch",
	"Receiver Branch",
	"Total Cost",
	"Shipment Date",
	"Status",
	"Requested",
	"Canceled",
	"Assigned Driver For Pickup",
	"In Queue",
	"Dispatch",
	"Received",
	"Delivery In Queue",
	"Delivered",
	"Return In Queue",
	"Return In Dispatch",
	"Return In Received",
	"Return Delivered",
	"No Shipments Found",
	"Payment Success",
	"THANK YOU",
	"Email Verification",
	"Code",
	"Submit",
	"Add Fund",
	"Pay Now",
	"Transaction Limit:",
	"Charge:",
	"Payment By",
	"Amount",
	"Payment Success",
	"2 Step Security",
	"Two Factor Authenticator",
	"Disable Two Factor Authenticator",
	"Enable Two Factor Authenticator",
	"Google Authenticator",
	"Verify Your OTP",
	"Enter Google Authenticator Code",
	"DOWNLOAD APP",
	"Verify",
	"Close",
	"Copied:",
	"Transaction List",
	"Dashboard",
	"Transaction",
	"SL No",
	"Transaction ID",
	"Amount",
	"Remarks",
	"Time",
	"No Transactions Found",
	"Transaction ID",
	"Remark",
	"Select To Date",
	"Search",
	"Create Ticket",
	"Subject",
	"Message",
	"Submit Ticket",
	"Tickets Log",
	"Dashboard",
	"Create new ticket",
	"Subject",
	"Status",
	"Last Reply",
	"Action",
	"Open",
	"Answered",
	"Replied",
	"Closed",
	"View",
	"No Tickets Found",
	"Ticket# ",
	"Open",
	"Answered",
	"Customer Replied",
	"Closed",
	"View",
	"Confirmation",
	"Are you want to close ticket",
	"Close",
	"Confirm",
	"Shipment List",
	"Dashboard",
	"Shipment Id",
	"Shipment Type",
	"Sender Branch",
	"Receiver Branch",
	"From Country",
	"To Country",
	"Total Cost",
	"Shipment Date",
	"Status",
	"Action",
	"Internationally",
	"Create Shipment",
	"Details",
	"No Shipments Found",
	"Confirmation",
	"Are you sure to cancel this shipment request?",
	"No",
	"Yes",
	"Create New Shipment",
	"Dashboard",
	"Shipments List",
	"create shipment",
	"Create Shipment",
	"Back",
	"Drag & Drop files here or click to browse images",
	"Shipment List",
	"Dashboard",
	"Shipment List",
	"Create Shipment",
	"Back",
	"SL.",
	"Shipment Id",
	"Shipment Type",
	"Sender Branch",
	"Receiver Branch",
	"From State",
	"To State",
	"Total Cost",
	"Shipment Date",
	"Status",
	"Action",
	"Details",
	"Requested",
	"Canceled",
	"Assigned Driver For Pickup",
	"In Queue",
	"Dispatch",
	"Received",
	"Delivery In Queue",
	"Delivered",
	"Return In Queue",
	"Return In Dispatch",
	"Return In Received",
	"Return Delivered",
	"Are you sure to cancel this shipment request?",
	"No",
	"Yes",
	"Confirmation",
	"Are you sure to delete this shipment request?",
	"Shipment Refund Alert",
	"Create New Shipment",
	"Dashboard",
	"Shipments List",
	"create shipment",
	"Create Shipment",
	"Back",
	"Sender",
	"Receiver",
	"Select Sender",
	"Select Receiver",
	"Sender Information",
	"Receiver Information",
	"From State",
	"From City",
	"From Area",
	"To State",
	"To City",
	"To Area",
	"Package Type",
	"Package Variant",
	"Add Another Variant",
	"Remove",
	"Shipment Weight",
	"Price Calculation",
	"Delivery Cost",
	"Insurance Cost",
	"Total Cost",
	"Submit Shipment",
	"Cancel",
	"Add Parcel",
	"Parcel Name",
	"Parcel Quantity",
	"Parcel Weight",
	"Select Parcel Unit",
	"Package Details",
	"Add Another Parcel",
	"Shipment Image",
	"Drag & Drop files here or click to browse images",
	"Create Shipment",
	"Back",
	"Details",
	"shipment id",
	"All Shipments",
	"Drop Off",
	"Pickup",
	"Condition",
	"sender branch",
	"receiver branch",
	"shipment date",
	"delivery date",
	"Search",
	"View Shipment",
	"Shipment Details",
	"Dashboard",
	"Shipment Id",
	"All Shipments",
	"Back",
	"Print",
	"Shipment Details",
	"Shipment Type",
	"Shipment Date",
	"Estimate Delivery Date",
	"Sender",
	"Receiver",
	"Receive Amount",
	"Sender Branch",
	"Receiver Branch",
	"From Country",
	"From State",
	"From City",
	"From Area",
	"To Country",
	"To State",
	"To City",
	"To Area",
	"Payment Type",
	"Payment By",
	"Payment Status",
	"Shipment Status",
	"Dispatched Time",
	"Received Time",
	"Return Dispatched Time",
	"Return Received Time",
	"Return Delivered Time",
	"Delivered Time",
	"Payment To Sender",
	"Payment Receive Time",
	"Shipment Refund Date",
	"Shipment Refund Time",
	"Packing Service",
	"Parcel Information",
	"Parcel Name",
	"Quantity",
	"Parcel Type",
	"Total Unit",
	"Cost",
	"Total Price",
	"Shipment Attachments",
	"Discount",
	"Sub Total",
	"Pickup Cost",
	"Supply Cost",
	"Shipping Cost",
	"Tax",
	"Insurance",
	"Payable Amount",
	"Create Receiver",
	"Dashboard",
	"Receiver List",
	"create reveiver",
	"Select Branch",
	"Full name",
	"Username",
	"Email",
	"Phone",
	"Password",
	"Select Country",
	"Select State",
	"Select city",
	"Select Area",
	"Address",
	"Create",
	"Receiver Lists",
	"Dashboard",
	"Receiver List",
	"Create new receiver",
	"Name",
	"Branch",
	"Phone",
	"Email",
	"Join Date",
	"No Receiver Found",
	"Change Password",
	"Dashboard",
	"Current password",
	"Enter your current password",
	"Password",
	"Enter new password",
	"Repeat password",
	"Change Password",
	"Profile",
	"Dashboard",
	"Change Password",
	"Full Name",
	"full name",
	"Username",
	"username",
	"Email",
	"email",
	"Phone",
	"phone",
	"Preferred Language",
	"select language",
	"Address",
	"address",
	"Update",
	"Current Password",
	"Enter Current Password",
	"New Password",
	"Enter New Password",
	"Confirm Password",
	"Confirm Password",
	"Update Password",
	"Payout",
	"Select Bank Currency",
	"Select Currency",
	"Select Recipient Type",
	"Select Recipient",
	"Email",
	"phone",
	"Paypal Id",
	"Send Request",
	"Details",
	"Payout Method",
	"Request Amount",
	"Charge Amount",
	"Total Payable",
	"Available Balance",
	"Exchange rate",
	"You will get",
	"Choose File",
	"Change File",
	"Payout List",
	"Home",
	"Payout History",
	"SL",
	"Transaction ID",
	"Amount",
	"Status",
	"Created time",
	"Action",
	"Pending",
	"Generated",
	"Payment Done",
	"Canceled",
	"Confirm",
	"No Payouts Found",
	"Type Here",
	"All Payment",
	"Pending Payment",
	"Complete Payment",
	"Rejected Payment",
	"Search",
	"Transaction ID",
	"Gateway",
	"Amount",
	"Charge",
	"Status",
	"Time",
	"Detail",
	"No Data Found!",
	"Details",
	"Transactions",
	"Admin Feedback",
	"Close",
	"Payment Information",
	"PAYOUT NOW",
	"Transaction Limit",
	"Charge",
	"Payout By",
	"Amount",
	"Next",
	"Request Amount",
	"Charge Amount",
	"Total Payable",
	"Available Balance",
	"Additional Information To Withdraw Confirm",
	"Transaction Limit",
	"Charge",
	"Total Payable",
	"Available Balance",
	"Additional Information To Withdraw Confirm",
	"Confirm Now",
	"Select",
	"Change",
	"Remove",
	"Send Payout Request",
	"Withdraw your money from here",
	"Choose a payout method",
	"Amount",
	"Enter Amount",
	"Continue",
	"Details",
	"Fixed charge",
	"Percentage charge",
	"Min limit",
	"Max limit",
	"Transaction ID",
	"Min Amount",
	"Maximum Amount",
	"Select Date",
	"Filter",
	"Payout",
	"Select Transfer",
	"Select Currency",
	"Select Bank",
	"Send Request",
	"Exchange rate",
	"You will get",
	"Details",
	"Payout Method",
	"Request Amount",
	"Charge Amount",
	"Total Payable",
	"Available Balance",
	"Payout",
	"Select Bank Currency",
	"Select Currency",
	"Select Bank",
	"Send Request",
	"Exchange rate",
	"You will get",
	"Details",
	"Payout Method",
	"Request Amount",
	"Charge Amount",
	"Total Payable",
	"Available Balance",
	"Choose File",
	"Pay with",
	"Dashboard",
	"Your Card Information",
	"Enter your card number",
	"Enter the name on your card",
	"Submit",
	"Pay with",
	"Dashboard",
	"Payment Preview",
	"PLEASE SEND EXACTLY",
	":amount",
	":currency",
	"TO",
	":sendto",
	"SCAN TO SEND",
	"Pay with",
	"Dashboard",
	"Please Pay",
	"Pay Now",
	"Pay with",
	"Dashboard",
	"Please Pay",
	"Pay with Khalti",
	"Please follow the instruction below",
	"You have requested to deposit",
	"Please pay",
	"for successful payment",
	"Confirm Now",
	"Pay with ",
	"Dashboard",
	"Please Pay",
	"Pay Now",
	"Payment Success",
	"THANK YOU",
	"Pay with PAYPAL",
	"Dashboard",
	"Please Pay",
	"Pay with ",
	"Dashboard",
	"Please Pay",
	"Shipment Type",
	"Estimate Delivery Date",
	"Sender Branch",
	"Receiver Branch",
	"Sender",
	"Receiver",
	"From Country",
	"Select State",
	"Select City",
	"To Country",
	"Payment Success",
	"THANK YOU",
	"Select Area",
	"To State",
	"Select City",
	"Select Area",
	"Payment By",
	"Payment Type",
	"Packing Service",
	"Yes",
	"No",
	"Add More",
	"Select package",
	"Select Variant",
	"price",
	"quantity",
	"total cost",
	"Select package",
	"Select Variant",
	"price",
	"quantity",
	"total cost",
	"Parcel Details",
	"parcel details",
	"Parcel Name",
	"Parcel Quantity",
	"Parcel Type",
	"Select Parcel Type",
	"Select Parcel Unit",
	"Cost per unit",
	"Total Unit",
	"Total Cost",
	"kg",
	"Dimensions",
	"Length x Width x Height",
	"optional",
	"Parcel Name",
	"Parcel Quantity",
	"Parcel Type",
	"Select Parcel Type",
	"Select Parcel Unit",
	"Cost per unit",
	"Total Unit",
	"Total Cost",
	"kg",
	"Dimensions",
	"optional",
	"Attatchments",
	"Summary",
	"Subtotal",
	"Pickup Cost",
	"Supply Cost",
	"Shipping Cost",
	"Tax",
	"Insurance",
	"Total Pay",
	"Save",
	"Add Fund",
	"You can deposit money into your own wallet",
	"Deposit",
	"Amount",
	"Select Payment Method",
	"Available Balance",
	"Transfer Charge",
	"Payable Amount",
	"Received",
	"New Balance",
	"Min Deposit Limit",
	"Max Deposit Limit",
	"Fund List",
	"Home",
	"Fund History",
	"SL",
	"Method",
	"Transaction ID",
	"Requested Amount",
	"Status",
	"Created time",
	"Success",
	"Pending",
	"Fund Requested List",
	"Dashboard",
	"Fund Added List",
	"SL",
	"Method",
	"Transaction ID",
	"Requested Amount",
	"Status",
	"Created time",
	"N/A",
	"Pending",
	"Rejected",
	"No data found",
	"Transaction ID",
	"Min Amount",
	"Maximum Amount",
	"Select Date",
	"Search",
	"Add Fund Preview",
	"Preview Deposit",
	"Gateway",
	"Name",
	"Currency",
	"Amount",
	"Charge",
	"Payable amount",
	"Confirm",
	"Happy Clients",
	"Total Shipments",
	"about_image",
	"READ MORE",
	'Email Address',
	'Subscribe',
	"banner_heading",
	'logo',
	'Quick Links',
	'Coverage Area',
	'FAQ',
	'Blog',
	'Contact us',
	'enter email',
	'Subscribe',
	'All rights reserved',
	'by',
	'Login',
	'All rights reserved by',
	"Dashboard",
	"Shipments",
	"All Shipments",
	"In Queue",
	"Dispatch",
	"Received",
	"Delivered",
	"Shipment Request",
	"Receiver List",
	"Add Fund",
	"Fund History",
	"Payout",
	"Payout History",
	"Money Transfer",
	"Transaction",
	"Support Ticket",
	"Payment Success",
    "THANK YOU",
	'Login',
	'Sing In',
	'Username or Email',
	'Password',
	'Remember me',
	'Forgot Password',
	'Log In',
	'Create account',
	'Sign Up',
	'register',
	'Enter Full Name',
	'Enter Email',
	'Enter Username',
	'Your Phone Number',
	'Password',
	'Re-type Password',
	'I Agree with the Terms & conditions',
	'Create Account',
	'Already have an account?',
	'Login Here',
	'2 Step Verification',
	'twoFA security',
	'2 FA Verification',
	'2 FA Code',
	'Submit',
	'Varification Code',
	'Email Verification',
	'email verification',
	'Code',
	'Submit',
	"Didn't get code?",
	'Resend code',
	'SMS Verification',
	'Sms Verification',
	'sms verification',
	'Code',
	'Submit',
	"Didn't get code?",
	'Resend code',
	'Change Password',
	'Current password',
	'Enter your current password',
	'Password',
	'Enter new password',
	'Repeat password',
	'Confirm Password',
	'Please confirm your password before continuing.',
	'Password',
	'Forgot Your Password?',
	'Reset password',
	'Forget password',
	'Email address',
	'Submit',
	'New Password',
	'Confirm New Password',
	'Reset Password',
	'month',
	'than',
	'day',
];
return $arr;
